import { chromium } from 'playwright-core';
const EXE = process.env.HOME + '/.cache/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell';
const browser = await chromium.launch({ executablePath: EXE });
let page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
await page.waitForTimeout(1000);
await page.evaluate(() => window.scrollTo(0, 3300));
await page.waitForTimeout(1200);
await page.screenshot({ path: './qa/qa-parishlife-cards.png' });
await page.evaluate(() => window.scrollTo(0, 4300));
await page.waitForTimeout(1200);
await page.screenshot({ path: './qa/qa-story.png' });
await page.close();
page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.goto('http://localhost:4173/contact', { waitUntil: 'networkidle' });
await page.waitForTimeout(1000);
await page.evaluate(() => window.scrollTo(0, 900));
await page.waitForTimeout(1000);
await page.screenshot({ path: './qa/qa-contact-mid-m.png' });
await browser.close();
console.log('done');
