import { chromium } from 'playwright-core';
const EXE = process.env.HOME + '/.cache/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell';
const b = await chromium.launch({ executablePath: EXE });
const errs = [];
const BASE = 'http://localhost:4173/lourde-matha-website';
const d = await (await b.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
d.on('pageerror', e => errs.push(e.message));
await d.goto(BASE + '/', { waitUntil: 'networkidle' });
await d.waitForTimeout(2500);
await d.screenshot({ path: '/tmp/h-desktop.png' });
const m = await (await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true })).newPage();
m.on('pageerror', e => errs.push('mobile: ' + e.message));
await m.goto(BASE + '/', { waitUntil: 'networkidle' });
await m.waitForTimeout(2500);
await m.screenshot({ path: '/tmp/h-mobile.png' });
console.log('ERRORS:', JSON.stringify(errs));
await b.close();
