import { chromium } from 'playwright-core';
const EXE = process.env.HOME + '/.cache/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell';
const b = await chromium.launch({ executablePath: EXE });
const errs = [];
const d = await (await b.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
d.on('pageerror', e => errs.push(e.message));
await d.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
await d.waitForTimeout(2000);
await d.screenshot({ path: '/tmp/nav-top.png', clip: { x: 900, y: 0, width: 540, height: 120 } });
await d.evaluate(() => window.scrollTo(0, 1200));
await d.waitForTimeout(1200);
await d.screenshot({ path: '/tmp/nav-pill.png', clip: { x: 300, y: 0, width: 840, height: 140 } });
console.log('ERRORS:', JSON.stringify(errs));
await b.close();
