import { chromium } from 'playwright-core';
const EXE = process.env.HOME + '/.cache/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell';
const b = await chromium.launch({ executablePath: EXE });
const errs = [];
const d = await (await b.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
d.on('pageerror', e => errs.push(e.message));
const BASE = 'http://localhost:4173/lourde-matha-website';
await d.goto(BASE + '/about', { waitUntil: 'networkidle' });
await d.waitForTimeout(800);
await d.evaluate(() => window.scrollTo(0, document.body.scrollHeight * 0.72));
await d.waitForTimeout(1500);
await d.screenshot({ path: '/tmp/r-sacraments.png' });
await d.goto(BASE + '/events', { waitUntil: 'networkidle' });
await d.waitForTimeout(800);
await d.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
await d.waitForTimeout(1500);
await d.screenshot({ path: '/tmp/r-videos.png' });
await d.goto(BASE + '/gallery', { waitUntil: 'networkidle' });
await d.waitForTimeout(1500);
await d.screenshot({ path: '/tmp/r-gallery.png' });
console.log('ERRORS:', JSON.stringify(errs));
await b.close();
